version: "3.2"
services:
  postgres:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - internal

  phoenix:
    container_name: "phoenixdev"
    image: bitwalker/alpine-elixir-phoenix:1.7.3
    #command: sh -c "cd /data/apps/neoscan_web && mix local.hex --force && mix deps.update tzdata && mix phx.server"
    command: sh -c "while true; do echo Alive; sleep 100; done"
    volumes:
      - ./:/data
    ports:
      - 4000:4000
    networks:
      - web
      - internal
    labels:  # used for Traefik dynamic configuration
      - traefik.enable=true
      - traefik.backend=phoenix
      - traefik.frontend.rule=Host:neoscan.blockshain.com
      - traefik.port=4000
      - "traefik.docker.network=web"

networks:
  web:
    external:
      name: web
  internal:
    driver: bridge